import fse from 'fs-extra';
import glob from 'glob';
import rm from 'rimraf';
import replaceInFile from 'replace-in-file';

function copy(source, target) {
	fse.copySync(source, target);
}

const sveltosisString = 'sveltosis/';

rm('./content/**/*', {}, () => {
	glob('output/**/*', { nodir: true }, function (er, files) {
		files.forEach((file) => {
			let split = file.split('/');
			let name = split.pop();
			let framework = split[1];
			let path = `./content/${file.substring(file.indexOf(sveltosisString) + sveltosisString.length, file.indexOf(name))}${framework}/${name}`;
			copy(`./${file}`, path);

			if (framework === 'qwik') {
				replaceInFile({
					files: path,
					from: '// GENERATED BY MITOSIS\n\n',
					to: '',
				});
			}
		});

		glob('sveltosis/**/*.svelte', { nodir: true }, function (er, files) {
			files.forEach((file) => {
				let split = file.split('/');
				let name = split.pop();
				let framework = 'svelte';
				let path = `./content/${file.substring(file.indexOf(sveltosisString) + sveltosisString.length, file.indexOf(name))}${framework}/${name}`;
				copy(`./${file}`, path);
			});
		});
	});
});
